- name: run make
  command: make
  args:
    chdir: "{{ awesome_full_build_dir }}"

- name: run cmake on awesome tarball
  command: >
    cmake build/.
  environment:
    DCMAKE_PREFIX_PATH: /usr
    DSYSCONFDIR: /etc
  args:
    chdir: "{{ awesome_full_build_dir }}"

- name: install awesome
  command: make install
  sudo: yes
  args:
    chdir: "{{ awesome_full_build_dir }}"

- name: remove source files
  tags: awe
  file: path="{{ item }}"
        state=absent
  with_items:
    - "{{ awesome_build_dir }}"
    - "{{ awesome_build_dir }}.tar.bz2"
